---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-config-v1
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi