---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tv
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: tv
      version: 12.2.0
      sourceRef:
        kind: HelmRepository
        name: jrbeverly-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/jrbeverly/tv
      tag: v3.0.6.1265
    env:
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: "tv.in.jrbeverly.dev"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "tv.in.jrbeverly.dev"
      api:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: "tv.in.jrbeverly.dev"
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "tv.in.jrbeverly.dev"
    podSecurityContext:
      supplementalGroups:
      - 100
    persistence:
      config:
        enabled: true
        existingClaim: tv-config-v1
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi