---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "cloudflare@jrbeverly.me"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          email: "cloudflare@jrbeverly.me"
          apiTokenSecretRef:
            name: cloudflare-token-secret
            key: cloudflare-token
